# Nashville Housing Data: End-to-End SQL Data Cleaning & Analysis

> **Author:** Benard Mwinzi  
> **Dataset:** Nashville Housing (56,477 records)  
> **Tools:** MySQL · Python · Jupyter Notebook  
> **Domain:** Real Estate Analytics

---

## Project Overview

This project demonstrates **professional-grade data cleaning and feature engineering** on a real-world Nashville housing dataset using **MySQL inside Jupyter Notebook**. One of the major challenges faced by data professionals is that raw transactional data is rarely analysis-ready. This pipeline transforms messy, incomplete records into a clean, structured, and analytics-ready dataset.

---

## Goals

| # | Goal | Technique Used |
|---|------|----------------|
| 1 | Standardize the `SaleDate` format | `DATE()` function + `UPDATE` |
| 2 | Impute missing `PropertyAddress` values | Self-join on `ParcelID` + `INNER JOIN` UPDATE |
| 3 | Decompose address columns into atomic fields | `SUBSTRING_INDEX()` + `ALTER TABLE` |
| 4 | Normalize the `SoldAsVacant` flag (Y/N) | `CASE WHEN` + `UPDATE` |
| 5 | Remove PII columns | `ALTER TABLE DROP COLUMN` |
| 6 | Engineer a `SaleMonth` feature | `EXTRACT(MONTH FROM ...)` + `UPDATE` |
| 7 | Validate data integrity at each step | `COUNT(*)`, `SELECT WHERE`, GROUP BY checks |
| 8 | Produce exploratory summaries | Aggregations, post-clean analysis |

---
## 1. Environment Setup

We use `pymysql` to connect to MySQL and `pandas` to display query results as DataFrames.
Two helper functions — `query()` and `execute()` — keep every cell clean and consistent:
- **`query(sql)`** — runs a SELECT and returns a styled DataFrame
- **`execute(sql)`** — runs DDL / DML (CREATE, UPDATE, ALTER, DROP) and prints rows affected

In [ ]:
import pymysql
import pandas as pd
from sqlalchemy import create_engine, text

# ── Connection ────────────────────────────────────────────────────────────────
engine = create_engine(
    'mysql+pymysql://root:mypassword@localhost/housing_data',
    connect_args={'local_infile': True}
)

# Keep a raw pymysql connection for LOAD DATA INFILE only
conn = pymysql.connect(
    host='localhost',
    user='root',
    password='mypassword',
    database='housing_data',
    local_infile=True
)

# ── Helper: SELECT queries → DataFrame ───────────────────────────────────────
def query(sql):
    with engine.connect() as connection:
        return pd.read_sql(text(sql), connection)

# ── Helper: DDL / DML → rows affected ────────────────────────────────────────
def execute(sql):
    with engine.connect() as connection:
        result = connection.execute(text(sql))
        connection.commit()
        print(f'OK — rows affected: {result.rowcount}')

print('Connected successfully.')

Connected successfully.

---
## 2. Database & Table Setup

We create a fresh `housing_data` table with explicit data types matching the CSV schema.
Choosing correct types upfront (e.g., `DECIMAL` for prices, `DATE` for dates)
prevents silent type-coercion bugs downstream.

In [25]:
execute('DROP TABLE IF EXISTS housing_data;')

OK — rows affected: 0

In [26]:
execute("""
CREATE TABLE housing_data (
    UniqueID        INT           NOT NULL,
    ParcelID        VARCHAR(50),
    LandUse         VARCHAR(50),
    PropertyAddress VARCHAR(70),
    SaleDate        VARCHAR(30),
    SalePrice       DECIMAL(15,2),
    LegalReference  VARCHAR(50),
    SoldAsVacant    VARCHAR(5),
    OwnerName       VARCHAR(70),
    OwnerAddress    VARCHAR(70),
    Acreage         DECIMAL(8,3),
    TaxDistrict     VARCHAR(30),
    LandValue       DECIMAL(15,2),
    BuildingValue   DECIMAL(15,2),
    TotalValue      DECIMAL(15,2),
    YearBuilt       INT,
    Bedrooms        INT,
    FullBath        INT,
    HalfBath        INT,
    UNIQUE  (UniqueID),
    PRIMARY KEY (UniqueID)
)
""")

OK — rows affected: 0

In [27]:
# Confirm schema
query('DESCRIBE housing_data;')

              Field           Type Null  Key Default Extra
0          UniqueID            int   NO  PRI    None
1          ParcelID    varchar(50)  YES         None
2           LandUse    varchar(50)  YES         None
3   PropertyAddress    varchar(70)  YES         None
4          SaleDate    varchar(30)  YES         None
5         SalePrice  decimal(15,2)  YES         None
6    LegalReference    varchar(50)  YES         None
7      SoldAsVacant     varchar(5)  YES         None
8         OwnerName    varchar(70)  YES         None
9      OwnerAddress    varchar(70)  YES         None
10          Acreage   decimal(8,3)  YES         None
11      TaxDistrict    varchar(30)  YES         None
12        LandValue  decimal(15,2)  YES         None
13    BuildingValue  decimal(15,2)  YES         None
14       TotalValue  decimal(15,2)  YES         None
15        YearBuilt            int  YES         None
16         Bedrooms            int  YES         None
17         FullBath            int  YES         None
18         HalfBath            int  YES         None

---
## 3. Data Import

In [28]:
# Load data from CSV file into the table
execute("""
LOAD DATA LOCAL INFILE 'D:/MySQL/Housing Data Cleaning and Analysis/dataset/Nashville_Housing_Data.csv'
INTO TABLE housing_data
FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\\n'
IGNORE 1 LINES
""")

OK — rows affected: 56477

---
## 4. Initial Exploratory Data Assessment

Before cleaning, we audit the data to understand its shape, distributions, and quality issues.

In [29]:
# 4.1  Total row count
query('SELECT COUNT(*) AS total_rows FROM housing_data;')

   total_rows
0       56477

In [30]:
# 4.2  First 5 rows: quick sanity check
query('SELECT * FROM housing_data LIMIT 5;')

,UniqueID,ParcelID,LandUse,PropertyAddress,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,OwnerAddress,Acreage,TaxDistrict,LandValue,BuildingValue,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath
0,0,105 03 0D 008.00,RESIDENTIAL CONDO,"1208 3RD AVE S, NASHVILLE","January 24, 2013",132000.0,20130128-0008725,No,,,0.00,,0.0,0.0,0.0,0,0,0,0
1,1,105 11 0 080.00,SINGLE FAMILY,"1802 STEWART PL, NASHVILLE","January 11, 2013",191500.0,20130118-0006337,No,"STINSON, LAURA M.","1802 STEWART PL, NASHVILLE, TN",0.17,URBAN SERVICES DISTRICT,32000.0,134400.0,168300.0,1941,2,1,0
2,2,118 03 0 130.00,SINGLE FAMILY,"2761 ROSEDALE PL, NASHVILLE","January 18, 2013",202000.0,20130124-0008033,No,"NUNES, JARED R.","2761 ROSEDALE PL, NASHVILLE, TN",0.11,CITY OF BERRY HILL,34000.0,157800.0,191800.0,2000,3,2,1
3,3,119 01 0 479.00,SINGLE FAMILY,"224 PEACHTREE ST, NASHVILLE","January 18, 2013",32000.0,20130128-0008863,No,"WHITFORD, KAREN","224 PEACHTREE ST, NASHVILLE, TN",0.17,URBAN SERVICES DISTRICT,25000.0,243700.0,268700.0,1948,4,2,0
4,4,119 05 0 186.00,SINGLE FAMILY,"316 LUTIE ST, NASHVILLE","January 23, 2013",102000.0,20130131-0009929,No,"HENDERSON, JAMES P. & LYNN P.","316 LUTIE ST, NASHVILLE, TN",0.34,URBAN SERVICES DISTRICT,25000.0,138100.0,164800.0,1910,2,1,0

In [31]:
# 4.3  Null / blank audit across key columns
query("""
SELECT
    SUM(PropertyAddress = '' OR PropertyAddress IS NULL) AS missing_PropertyAddress,
    SUM(OwnerName       = '' OR OwnerName IS NULL)       AS missing_OwnerName,
    SUM(OwnerAddress    = '' OR OwnerAddress IS NULL)    AS missing_OwnerAddress,
    SUM(SaleDate IS NULL)                               AS missing_SaleDate,
    SUM(SalePrice IS NULL OR SalePrice = 0)             AS zero_SalePrice,
    SUM(YearBuilt IS NULL OR YearBuilt = 0)             AS missing_YearBuilt
FROM housing_data
""")

,missing_PropertyAddress,missing_OwnerName,missing_OwnerAddress,missing_SaleDate,zero_SalePrice,missing_YearBuilt
0,29.0,31216.0,30462.0,0.0,7.0,32314.0

In [32]:
# 4.4  Distribution of land use types
query("""
SELECT LandUse, COUNT(*) AS count
FROM housing_data
GROUP BY LandUse
ORDER BY count DESC
LIMIT 10
""")

                   LandUse  count
0            SINGLE FAMILY  34197
1        RESIDENTIAL CONDO  14080
2  VACANT RESIDENTIAL LAND   3547
3          VACANT RES LAND   1549
4                   DUPLEX   1373
5            ZERO LOT LINE   1048
6                    CONDO    247
7   RESIDENTIAL COMBO/MISC     95
8                  TRIPLEX     92
9                 QUADPLEX     39

---
## 5. Cleaning Step 1 — Standardize the Date Format

**Problem:** The `SaleDate` column was imported from a mixed format (e.g., `April 9, 2013`).
We explicitly cast it to guarantee ISO 8601 format (`YYYY-MM-DD`).

**Solution:** Rewrite the column using the `DATE()` function.

In [35]:
# Convert SaleDate from 'September 26, 2016' format to proper DATE
execute("UPDATE housing_data SET SaleDate = STR_TO_DATE(SaleDate, '%M %d, %Y');")

OK — rows affected: 56477

In [36]:
# Now change the column type to DATE
execute("ALTER TABLE housing_data MODIFY COLUMN SaleDate DATE;")

OK — rows affected: 56477

In [37]:
# Verify
query("SELECT SaleDate FROM housing_data LIMIT 5;")

     SaleDate
0  2013-01-24
1  2013-01-11
2  2013-01-18
3  2013-01-18
4  2013-01-23

---
## 6. Cleaning Step 2 — Impute Missing Property Addresses

**Problem:** 29 rows have a blank `PropertyAddress`.

**Insight:** Properties with the same `ParcelID` share a physical location.
A self-join can borrow the address from a sibling row in the same parcel.

**Technique:** Self-join on `ParcelID` → `CREATE VIEW` → `INNER JOIN UPDATE`

In [45]:
# How many rows are missing PropertyAddress?
query("""
SELECT COUNT(*) AS missing_count
FROM housing_data
WHERE PropertyAddress = '' OR PropertyAddress IS NULL
""")

   missing_count
0             29

In [46]:
# Preview the self-join logic before committing
query("""
SELECT
    a.UniqueID,
    a.ParcelID,
    a.PropertyAddress AS current_address,
    b.PropertyAddress AS donor_address
FROM housing_data a
JOIN housing_data b
    ON  a.ParcelID  = b.ParcelID
    AND a.UniqueID <> b.UniqueID
WHERE a.PropertyAddress = ''
LIMIT 10
""")

,UniqueID,ParcelID,current_address,donor_address
0,11478,092 13 0 322.00,,"237 37TH AVE N, NASHVILLE"
1,47293,043 04 0 014.00,,"112 HILLER DR, OLD HICKORY"
2,45290,026 05 0 017.00,,"208 EAST AVE, GOODLETTSVILLE"
3,40678,042 13 0 075.00,,"222 FOXBORO DR, MADISON"
4,43151,052 08 0A 320.00,,"608 SANDY SPRING TRL, MADISON"
5,45774,107 13 0 107.00,,"1205 THOMPSON PL, NASHVILLE"
6,43080,033 06 0 041.00,,"1129 CAMPBELL RD, GOODLETTSVILLE"
7,8126,093 08 0 054.00,,"700 GLENVIEW DR, NASHVILLE"
8,45295,033 06 0A 002.00,,"1116 CAMPBELL RD, GOODLETTSVILLE"
9,15886,109 04 0A 080.00,,"2537 JANALYN TRCE, HERMITAGE"

In [47]:
# Create a view to hold the resolved addresses
execute('DROP VIEW IF EXISTS updated_address;')

execute("""
CREATE VIEW updated_address AS
SELECT
    a.UniqueID,
    a.ParcelID,
    IF(a.PropertyAddress = '', b.PropertyAddress, a.PropertyAddress) AS resolved_address
FROM housing_data a
JOIN housing_data b
    ON  a.ParcelID  = b.ParcelID
    AND a.UniqueID <> b.UniqueID
WHERE a.PropertyAddress = ''
""")

OK — rows affected: 0
OK — rows affected: 0

In [48]:
# Apply: write resolved addresses back into housing_data
execute("""
UPDATE housing_data
INNER JOIN updated_address
    ON  housing_data.ParcelID = updated_address.ParcelID
    AND housing_data.PropertyAddress = ''
SET housing_data.PropertyAddress = updated_address.resolved_address
""")

OK — rows affected: 29

In [49]:
# Verify: must return 0
query("""
SELECT COUNT(*) AS still_missing
FROM housing_data
WHERE PropertyAddress = '' OR PropertyAddress IS NULL
""")

   still_missing
0              0

In [50]:
# Integrity check: row count must remain 56,477
query('SELECT COUNT(*) AS total_rows FROM housing_data;')

   total_rows
0       56477

---
## 7. Cleaning Step 3 — Decompose Address Columns into Atomic Fields

**Problem:**
- `PropertyAddress` stores `street, city` in one column
- `OwnerAddress` stores `street, city, state` in one column

**Solution:** Use `SUBSTRING_INDEX()` to split on the comma delimiter into separate atomic columns.
This is essential for city-level filtering and geographic aggregation.

### 7a. Split PropertyAddress

In [51]:
# Preview the split before altering the table
query("""
SELECT
    PropertyAddress,
    SUBSTRING_INDEX(PropertyAddress, ',', 1)        AS PropertyStreet,
    TRIM(SUBSTRING_INDEX(PropertyAddress, ',', -1)) AS PropertyCity
FROM housing_data
LIMIT 5
""")

                PropertyAddress     PropertyStreet PropertyCity
0    1208  3RD AVE S, NASHVILLE    1208  3RD AVE S    NASHVILLE
1   1802  STEWART PL, NASHVILLE   1802  STEWART PL    NASHVILLE
2  2761  ROSEDALE PL, NASHVILLE  2761  ROSEDALE PL    NASHVILLE
3  224  PEACHTREE ST, NASHVILLE  224  PEACHTREE ST    NASHVILLE
4      316  LUTIE ST, NASHVILLE      316  LUTIE ST    NASHVILLE

In [52]:
execute("""
ALTER TABLE housing_data
ADD PropertyStreet VARCHAR(60),
ADD PropertyCity   VARCHAR(30)
""")

OK — rows affected: 0

In [53]:
execute("""
UPDATE housing_data
SET
    PropertyStreet = SUBSTRING_INDEX(PropertyAddress, ',', 1),
    PropertyCity   = TRIM(SUBSTRING_INDEX(PropertyAddress, ',', -1))
""")

OK — rows affected: 56477

In [54]:
execute('ALTER TABLE housing_data DROP COLUMN PropertyAddress;')

OK — rows affected: 0

### 7b. Split OwnerAddress (street · city · state)

In [55]:
# Preview the three-part split
query("""
SELECT
    OwnerAddress,
    SUBSTRING_INDEX(OwnerAddress, ',', 1)                                    AS OwnerStreet,
    TRIM(SUBSTRING_INDEX(SUBSTRING_INDEX(OwnerAddress, ',', -2), ',', 1))   AS OwnerCity,
    TRIM(SUBSTRING_INDEX(OwnerAddress, ',', -1))                             AS OwnerState
FROM housing_data
WHERE OwnerAddress <> ''
LIMIT 5
""")

                       OwnerAddress        OwnerStreet  OwnerCity OwnerState
0   1802  STEWART PL, NASHVILLE, TN   1802  STEWART PL  NASHVILLE         TN
1  2761  ROSEDALE PL, NASHVILLE, TN  2761  ROSEDALE PL  NASHVILLE         TN
2  224  PEACHTREE ST, NASHVILLE, TN  224  PEACHTREE ST  NASHVILLE         TN
3      316  LUTIE ST, NASHVILLE, TN      316  LUTIE ST  NASHVILLE         TN
4   2626  FOSTER AVE, NASHVILLE, TN   2626  FOSTER AVE  NASHVILLE         TN

In [56]:
execute("""
ALTER TABLE housing_data
ADD OwnerStreet VARCHAR(60),
ADD OwnerCity   VARCHAR(30),
ADD OwnerState  VARCHAR(10)
""")

OK — rows affected: 0

In [57]:
execute("""
UPDATE housing_data
SET
    OwnerStreet = SUBSTRING_INDEX(OwnerAddress, ',', 1),
    OwnerCity   = TRIM(SUBSTRING_INDEX(SUBSTRING_INDEX(OwnerAddress, ',', -2), ',', 1)),
    OwnerState  = TRIM(SUBSTRING_INDEX(OwnerAddress, ',', -1))
""")

OK — rows affected: 56477

In [58]:
execute('ALTER TABLE housing_data DROP COLUMN OwnerAddress;')

OK — rows affected: 0

In [59]:
# Confirm the new structure
query("""
SELECT UniqueID, PropertyStreet, PropertyCity, OwnerStreet, OwnerCity, OwnerState
FROM housing_data
WHERE OwnerStreet <> ''
LIMIT 5
""")

,UniqueID,PropertyStreet,PropertyCity,OwnerStreet,OwnerCity,OwnerState
0,1,1802 STEWART PL,NASHVILLE,1802 STEWART PL,NASHVILLE,TN
1,2,2761 ROSEDALE PL,NASHVILLE,2761 ROSEDALE PL,NASHVILLE,TN
2,3,224 PEACHTREE ST,NASHVILLE,224 PEACHTREE ST,NASHVILLE,TN
3,4,316 LUTIE ST,NASHVILLE,316 LUTIE ST,NASHVILLE,TN
4,5,2626 FOSTER AVE,NASHVILLE,2626 FOSTER AVE,NASHVILLE,TN

---
## 8. Cleaning Step 4 — Normalize the SoldAsVacant Flag

**Problem:** The `SoldAsVacant` column has 4 inconsistent values: `Yes`, `No`, `Y`, `N`.

**Solution:** Standardize to `Y` and `N` using a `CASE WHEN` update.
Always audit distinct values and their counts before making changes.

In [60]:
# Audit: see all distinct values and frequencies
query("""
SELECT SoldAsVacant, COUNT(*) AS count
FROM housing_data
GROUP BY SoldAsVacant
ORDER BY count DESC
""")

  SoldAsVacant  count
0           No  51403
1          Yes   4623
2            N    399
3            Y     52

In [61]:
# Normalize: map Yes/Y to 'Y', No/N to 'N'
execute("""
UPDATE housing_data
SET SoldAsVacant = CASE
    WHEN SoldAsVacant IN ('Yes', 'Y') THEN 'Y'
    ELSE 'N'
END
""")

OK — rows affected: 56477

In [62]:
# Verify: only 'Y' and 'N' should remain
query("""
SELECT SoldAsVacant, COUNT(*) AS count
FROM housing_data
GROUP BY SoldAsVacant
""")

  SoldAsVacant  count
0            N  51802
1            Y   4675

---
## 9. Cleaning Step 5 — Remove Personally Identifiable Information (PII)

**PII columns identified:**
- `OwnerName` — individual legal names (direct identifier)
- `OwnerStreet` — owner home street address (locates where a person lives)

**Rationale:** These fields have no analytical value for market-level housing analysis
and increase privacy risk. City and state granularity is sufficient for geographic analysis.

> Best practice: document the decision and obtain data-owner approval before dropping columns.

In [63]:
execute("""
ALTER TABLE housing_data
DROP COLUMN OwnerName,
DROP COLUMN OwnerStreet
""")

OK — rows affected: 0

In [64]:
# Confirm the schema after PII removal
query('DESCRIBE housing_data;')

             Field           Type Null  Key Default Extra
0         UniqueID            int   NO  PRI    None
1         ParcelID    varchar(50)  YES         None
2          LandUse    varchar(50)  YES         None
3         SaleDate           date  YES         None
4        SalePrice  decimal(15,2)  YES         None
5   LegalReference    varchar(50)  YES         None
6     SoldAsVacant     varchar(5)  YES         None
7          Acreage   decimal(8,3)  YES         None
8      TaxDistrict    varchar(30)  YES         None
9        LandValue  decimal(15,2)  YES         None
10   BuildingValue  decimal(15,2)  YES         None
11      TotalValue  decimal(15,2)  YES         None
12       YearBuilt            int  YES         None
13        Bedrooms            int  YES         None
14        FullBath            int  YES         None
15        HalfBath            int  YES         None
16  PropertyStreet    varchar(60)  YES         None
17    PropertyCity    varchar(30)  YES         None
18       OwnerCity    varchar(30)  YES         None
19      OwnerState    varchar(10)  YES         None

---
## 10. Cleaning Step 6 — Feature Engineering: SaleMonth Column

**Purpose:** Pre-computing `SaleMonth` as a stored column means analysts do not need to call
`EXTRACT()` in every aggregation query. This improves query performance and readability.

**Technique:** `EXTRACT(MONTH FROM ...)` + `ALTER TABLE ADD` + `UPDATE`

In [65]:
# Preview the extraction
query("""
SELECT SaleDate, EXTRACT(MONTH FROM SaleDate) AS SaleMonth
FROM housing_data
ORDER BY SaleDate DESC
LIMIT 5
""")

     SaleDate  SaleMonth
0  2019-12-13         12
1  2019-05-16          5
2  2016-10-31         10
3  2016-10-31         10
4  2016-10-31         10

In [66]:
execute('ALTER TABLE housing_data ADD SaleMonth TINYINT;')

OK — rows affected: 0

In [67]:
execute('UPDATE housing_data SET SaleMonth = EXTRACT(MONTH FROM SaleDate);')

OK — rows affected: 56477

In [68]:
# Distribution of sales by month (1=Jan ... 12=Dec)
query("""
SELECT SaleMonth, COUNT(*) AS transactions
FROM housing_data
GROUP BY SaleMonth
ORDER BY SaleMonth
""")

    SaleMonth  transactions
0           1          3227
1           2          2778
2           3          4474
3           4          5223
4           5          5932
5           6          6593
6           7          5471
7           8          5620
8           9          5451
9          10          4822
10         11          3114
11         12          3772

---
## 11. Final Schema & Data Quality Validation

A full quality audit on the cleaned dataset before any downstream analysis.

In [69]:
query('DESCRIBE housing_data;')

             Field           Type Null  Key Default Extra
0         UniqueID            int   NO  PRI    None
1         ParcelID    varchar(50)  YES         None
2          LandUse    varchar(50)  YES         None
3         SaleDate           date  YES         None
4        SalePrice  decimal(15,2)  YES         None
5   LegalReference    varchar(50)  YES         None
6     SoldAsVacant     varchar(5)  YES         None
7          Acreage   decimal(8,3)  YES         None
8      TaxDistrict    varchar(30)  YES         None
9        LandValue  decimal(15,2)  YES         None
10   BuildingValue  decimal(15,2)  YES         None
11      TotalValue  decimal(15,2)  YES         None
12       YearBuilt            int  YES         None
13        Bedrooms            int  YES         None
14        FullBath            int  YES         None
15        HalfBath            int  YES         None
16  PropertyStreet    varchar(60)  YES         None
17    PropertyCity    varchar(30)  YES         None
18       OwnerCity    varchar(30)  YES         None
19      OwnerState    varchar(10)  YES         None
20       SaleMonth        tinyint  YES         None

In [70]:
query('SELECT * FROM housing_data LIMIT 5;')

,UniqueID,ParcelID,LandUse,SaleDate,SalePrice,LegalReference,SoldAsVacant,Acreage,TaxDistrict,LandValue,...,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath,PropertyStreet,PropertyCity,OwnerCity,OwnerState,SaleMonth
0,0,105 03 0D 008.00,RESIDENTIAL CONDO,2013-01-24,132000.0,20130128-0008725,N,0.00,,0.0,...,0.0,0,0,0,0,1208 3RD AVE S,NASHVILLE,,,1
1,1,105 11 0 080.00,SINGLE FAMILY,2013-01-11,191500.0,20130118-0006337,N,0.17,URBAN SERVICES DISTRICT,32000.0,...,168300.0,1941,2,1,0,1802 STEWART PL,NASHVILLE,NASHVILLE,TN,1
2,2,118 03 0 130.00,SINGLE FAMILY,2013-01-18,202000.0,20130124-0008033,N,0.11,CITY OF BERRY HILL,34000.0,...,191800.0,2000,3,2,1,2761 ROSEDALE PL,NASHVILLE,NASHVILLE,TN,1
3,3,119 01 0 479.00,SINGLE FAMILY,2013-01-18,32000.0,20130128-0008863,N,0.17,URBAN SERVICES DISTRICT,25000.0,...,268700.0,1948,4,2,0,224 PEACHTREE ST,NASHVILLE,NASHVILLE,TN,1
4,4,119 05 0 186.00,SINGLE FAMILY,2013-01-23,102000.0,20130131-0009929,N,0.34,URBAN SERVICES DISTRICT,25000.0,...,164800.0,1910,2,1,0,316 LUTIE ST,NASHVILLE,NASHVILLE,TN,1

In [71]:
# Final quality metrics dashboard
query("""
SELECT
    COUNT(*)                                                   AS total_rows,
    SUM(PropertyStreet = '' OR PropertyStreet IS NULL)        AS blank_PropertyStreet,
    SUM(PropertyCity   = '' OR PropertyCity IS NULL)          AS blank_PropertyCity,
    COUNT(DISTINCT SoldAsVacant)                              AS sold_as_vacant_distinct_vals,
    SUM(SaleMonth IS NULL)                                    AS null_SaleMonth,
    MIN(SaleDate)                                             AS date_min,
    MAX(SaleDate)                                             AS date_max
FROM housing_data
""")

,total_rows,blank_PropertyStreet,blank_PropertyCity,sold_as_vacant_distinct_vals,null_SaleMonth,date_min,date_max
0,56477,0.0,0.0,2,0.0,2013-01-02,2019-12-13

---
## 12. Exploratory Analysis on Cleaned Data

With a clean dataset, we can now run meaningful analyses that would have been
unreliable or impossible on the raw data.

In [72]:
# 12.1  Average sale price by city
query("""
SELECT
    PropertyCity,
    COUNT(*)                  AS transactions,
    ROUND(AVG(SalePrice), 2)  AS avg_price,
    ROUND(MIN(SalePrice), 2)  AS min_price,
    ROUND(MAX(SalePrice), 2)  AS max_price
FROM housing_data
WHERE SalePrice > 0
GROUP BY PropertyCity
ORDER BY avg_price DESC
LIMIT 10
""")

     PropertyCity  transactions  avg_price  min_price   max_price
0       NASHVILLE         40275  366292.18       50.0  54278060.0
1       BRENTWOOD          1696  312258.06    35000.0   2562600.0
2         UNKNOWN             1  298000.00   298000.0    298000.0
3  GOODLETTSVILLE           734  289707.18      120.0    900000.0
4     NOLENSVILLE           494  287143.72    32000.0   3235790.0
5         ANTIOCH          6316  252227.07       35.0   5491000.0
6    MOUNT JULIET           183  243094.92    61000.0    635000.0
7       HERMITAGE          3133  200018.11     1500.0   5491000.0
8     OLD HICKORY          1415  191082.95     5000.0   1700000.0
9    WHITES CREEK            97  168434.26    20000.0    728000.0

In [73]:
# 12.2  Monthly sales volume: which months are busiest?
query("""
SELECT
    SaleMonth,
    COUNT(*)                 AS transactions,
    ROUND(AVG(SalePrice), 2) AS avg_price
FROM housing_data
WHERE SalePrice > 0
GROUP BY SaleMonth
ORDER BY SaleMonth
""")

    SaleMonth  transactions  avg_price
0           1          3227  667910.48
1           2          2778  246079.33
2           3          4474  266191.56
3           4          5223  300484.75
4           5          5932  297648.29
5           6          6592  300111.04
6           7          5469  321419.70
7           8          5620  320339.52
8           9          5451  306834.04
9          10          4819  275579.04
10         11          3113  335451.13
11         12          3772  406073.64

In [74]:
# 12.3  Average price by property type
query("""
SELECT
    LandUse,
    COUNT(*)                  AS count,
    ROUND(AVG(SalePrice), 2)  AS avg_price,
    ROUND(AVG(Acreage), 3)    AS avg_acreage
FROM housing_data
WHERE SalePrice > 0
GROUP BY LandUse
ORDER BY avg_price DESC
LIMIT 10
""")

                                  LandUse  count   avg_price  avg_acreage
0                  VACANT COMMERCIAL LAND     17  3235294.12        0.091
1  APARTMENT: LOW RISE (BUILT SINCE 1960)      2  2000000.00        1.170
2                         DAY CARE CENTER      2  1577500.00        1.625
3                                   CONDO    247  1260063.77        0.000
4     CONDOMINIUM OFC  OR OTHER COM CONDO     35  1254597.14        0.000
5                             PARKING LOT     11  1225336.36        0.322
6                     LIGHT MANUFACTURING      1  1200000.00       15.400
7                                  FOREST     10  1085330.00       20.083
8                                  CHURCH     34   820573.53        2.095
9                               GREENBELT     10   604938.50       19.160

In [75]:
# 12.4  Vacant vs non-vacant: price and volume comparison
query("""
SELECT
    SoldAsVacant,
    COUNT(*)                   AS transactions,
    ROUND(AVG(SalePrice), 2)   AS avg_price,
    ROUND(AVG(TotalValue), 2)  AS avg_assessed_value
FROM housing_data
WHERE SalePrice > 0
GROUP BY SoldAsVacant
""")

  SoldAsVacant  transactions  avg_price  avg_assessed_value
0            N         51795  328874.34           111584.02
1            Y          4675  308866.96            56692.52

In [76]:
# 12.5  Price trends by decade of construction
query("""
SELECT
    FLOOR(YearBuilt / 10) * 10 AS decade_built,
    COUNT(*)                   AS count,
    ROUND(AVG(SalePrice), 2)   AS avg_price,
    ROUND(AVG(TotalValue), 2)  AS avg_assessed_value
FROM housing_data
WHERE YearBuilt > 0 AND SalePrice > 0
GROUP BY decade_built
ORDER BY decade_built
""")

    decade_built  count   avg_price  avg_assessed_value
0           1790      1   500000.00           778900.00
1           1830      1  1550000.00           632200.00
2           1870      2   567450.00           369650.00
3           1880      1    80000.00           101800.00
4           1890     96   434741.38           357982.29
5           1900    123   337903.68           280337.54
6           1910    294   386853.39           332139.44
7           1920   1413   343502.80           289470.62
8           1930   2107   324325.43           267916.28
9           1940   2571   259495.50           214200.47
10          1950   5141   244663.09           202927.95
11          1960   3956   232427.54           191600.91
12          1970   2016   211973.23           178648.81
13          1980   2427   185073.56           156826.60
14          1990    931   286376.80           252209.10
15          2000    794   506929.03           443593.32
16          2010   2285   391957.39           476876.59

In [77]:
# 12.6  Year-over-year transaction volume and average price
query("""
SELECT
    YEAR(SaleDate)           AS year,
    COUNT(*)                 AS transactions,
    ROUND(AVG(SalePrice), 2) AS avg_price,
    ROUND(SUM(SalePrice), 2) AS total_volume
FROM housing_data
WHERE SalePrice > 0
GROUP BY YEAR(SaleDate)
ORDER BY year
""")

   year  transactions  avg_price  total_volume
0  2013         11292  244549.72  2.761455e+09
1  2014         14280  334226.92  4.772760e+09
2  2015         16827  398669.75  6.708416e+09
3  2016         14069  301025.70  4.235131e+09
4  2019             2  118500.00  2.370000e+05

In [78]:
# 12.7  Top 10 highest-value sales
query("""
SELECT
    UniqueID, PropertyStreet, PropertyCity,
    LandUse, SaleDate, SalePrice, Bedrooms, FullBath, YearBuilt
FROM housing_data
WHERE SalePrice > 0
ORDER BY SalePrice DESC
LIMIT 10
""")

,UniqueID,PropertyStreet,PropertyCity,LandUse,SaleDate,SalePrice,Bedrooms,FullBath,YearBuilt
0,25634,320 11TH AVE S,NASHVILLE,RESIDENTIAL CONDO,2014-12-17,54278060.0,0,0,0
1,25637,320 11TH AVE S,NASHVILLE,RESIDENTIAL CONDO,2014-12-17,54278060.0,0,0,0
2,25631,320 11TH AVE S,NASHVILLE,RESIDENTIAL CONDO,2014-12-17,54278060.0,0,0,0
3,25633,320 11TH AVE S,NASHVILLE,RESIDENTIAL CONDO,2014-12-17,54278060.0,0,0,0
4,25632,320 11TH AVE S,NASHVILLE,RESIDENTIAL CONDO,2014-12-17,54278060.0,0,0,0
5,25636,320 11TH AVE S,NASHVILLE,RESIDENTIAL CONDO,2014-12-17,54278060.0,0,0,0
6,25635,320 11TH AVE S,NASHVILLE,RESIDENTIAL CONDO,2014-12-17,54278060.0,0,0,0
7,35017,50 MCFERRIN AVE,NASHVILLE,RESIDENTIAL CONDO,2015-07-14,14100000.0,0,0,0
8,35016,52 MCFERRIN AVE,NASHVILLE,RESIDENTIAL CONDO,2015-07-14,14100000.0,0,0,0
9,35018,48 MCFERRIN AVE,NASHVILLE,RESIDENTIAL CONDO,2015-07-14,14100000.0,0,0,0

In [79]:
# 12.8  Average bedrooms and bathrooms by land use
query("""
SELECT
    LandUse,
    COUNT(*)                    AS count,
    ROUND(AVG(Bedrooms), 1)     AS avg_bedrooms,
    ROUND(AVG(FullBath), 1)     AS avg_full_baths,
    ROUND(AVG(SalePrice), 2)    AS avg_price
FROM housing_data
WHERE Bedrooms > 0 AND SalePrice > 0
GROUP BY LandUse
ORDER BY count DESC
LIMIT 10
""")

                    LandUse  count  avg_bedrooms  avg_full_baths  avg_price
0             SINGLE FAMILY  21378           3.1             1.9  284265.30
1                    DUPLEX   1190           3.9             2.4  227636.39
2             ZERO LOT LINE    844           2.4             1.6  118827.98
3   VACANT RESIDENTIAL LAND    264           3.5             2.8  217921.57
4           VACANT RES LAND    230           3.5             2.6  191956.50
5                   TRIPLEX     77           4.9             3.0  220512.47
6    RESIDENTIAL COMBO/MISC     37           3.5             2.5  329528.70
7                  QUADPLEX     34           6.1             3.9  297423.53
8  DORMITORY/BOARDING HOUSE     14           4.3             2.4  255662.64
9               SPLIT CLASS     12           4.3             2.8  530625.00

---
## 13. Conclusion & Key Takeaways

This project transformed a raw, messy real estate dataset into a clean, analysis-ready table.

| SQL Skill | Applied In |
|-----------|------------|
| DDL: `CREATE TABLE`, `ALTER TABLE`, `DROP COLUMN` | Schema design & evolution |
| DML: `UPDATE`, `SET`, `CASE WHEN` | Data transformation |
| Self-joins | Address imputation |
| `SUBSTRING_INDEX()`, `TRIM()`, `EXTRACT()` | String parsing & feature engineering |
| `CREATE VIEW` | Reusable intermediate logic |
| `GROUP BY`, aggregations | Exploratory summaries |
| Integrity checks (`COUNT`, `SUM IS NULL`) | Quality validation |

### Cleaned Dataset Summary

| Metric | Before | After |
|--------|--------|-------|
| Missing PropertyAddress rows | 29 | 0 |
| Distinct SoldAsVacant values | 4 | 2 |
| Compound address columns | 2 | 0 (split into 4 atomic columns) |
| PII columns | 2 | 0 |
| Engineered features | 0 | 1 (SaleMonth) |
| Total rows | 56,477 | 56,477 (no data lost) |
| Date format | Mixed | ISO 8601 YYYY-MM-DD |

The cleaned dataset is now ready for BI dashboards, predictive modelling, or statistical analysis.

In [80]:
# Closing the connection when done
conn.close()
print('Connection closed.')

Connection closed.